In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [395]:
def initialize_weights(X,Y):
    '''
    Input:
        X:Input dataset
        Y:Output Label
        
    Output:
        (W,b): A tuple containing zero initialized weights and bias
    '''
    
    nx=X.shape[0]
    W=np.zeros((1,nx))
    b=0
    return (W,b)

In [396]:
X=np.random.randn(10,5)
Y=np.array([[0,1,0,1,1]])
print(X,X.shape)
print(Y,Y.shape)

[[-0.11783332 -0.01019626  1.51513948 -1.30678613 -1.54888668]
 [-1.32992628  0.83867087 -0.12718312 -0.30409439  0.05737848]
 [ 0.8584816  -0.41655815 -1.08443734  0.90168388  0.35150646]
 [-0.18121718  1.21221386  0.50375548  0.39321191 -0.83239343]
 [ 0.78728078  1.73619699 -1.15818032 -1.16355088  1.61002012]
 [ 0.54140064 -1.47942387  0.0410408  -1.20398055  1.46760332]
 [ 0.45870554  0.31148382  1.07681513  0.15825904 -1.99596624]
 [ 1.88045671 -0.72316082 -0.05926425  2.02857442  1.15763139]
 [ 0.26597638 -1.34557769 -0.48739755  0.0935297  -0.32621853]
 [ 1.86923613 -1.04821609  0.03853083  0.38342816 -0.03627887]] (10, 5)
[[0 1 0 1 1]] (1, 5)


In [397]:
print(initialize_weights(X,Y))

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), 0)


In [398]:
def sigmoid(z):
    '''
    Input:
        Z:Array
    Output:
        sigmoid value on each element of Z
    '''
    return 1/(1+np.exp(-z))

In [399]:
def forward_propagate(parameters,X,Y):
    '''
    Input:
        parameters:A tuple containing weight and bias matrix
        X:Input Data
        Y:Output Labels
    Output:
        gradient:dictionary containing dw and db which is gradient of loss w.r.t w and b respectively
        Loss:Loss between predicted value and actual value
    '''
    m=X.shape[1]
    w=parameters[0]
    b=parameters[1]
    z=np.dot(w,X)+b
    a=sigmoid(z)
    
    Loss=-1/m*np.sum((Y*np.log(a)+(1-Y)*np.log(1-a)))
    dz=a-Y
    dw=1/m*np.dot(dz,X.T)
    db=1/m*np.sum(dz)
    
    gradient={'dw':dw,
             'db':db}
    
    return gradient,Loss

In [400]:
w, b, X, Y = np.array([[1., 2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
grad,cost=forward_propagate((w,b),X,Y)
print(grad)
print(cost)

{'dw': array([[0.99845601, 2.39507239]]), 'db': 0.001455578136784208}
5.801545319394553


In [402]:
def optimize(alpha,parameters,X,Y,num_iterations,printValue=False):
    '''
    Input:
        alpha:learning rate for our modek
        parameters:A tuple containing weight and bias
        X:Input Data
        Y:Output Labels
        num_iterations: Number of iterations upto which model is run
        printValue:parameter whether or not to print the value of cost after every 100 iterations (default:False)
    Output:
        costList: List Of costs after every 100 iterations
        param: Tuple of parameters(weight and bias) after applying gradient descent
        grads: dictionary containing the value of dw and db after applying gradient descent
    '''
    w=parameters[0]
    b=parameters[1]
    costList=[]
    for i in range(num_iterations):
        
        gradient,cost=forward_propagate((w,b),X,Y)
        dw=gradient['dw']
        db=gradient['db']
        w=w-alpha*dw
        b=b-alpha*db
        if(i%100==0):
            if(printValue):
                print(cost)
            costList.append(cost)
    param=(w,b)
    grads={'dw':dw,
          'db':db}
    return costList,param,grads

In [403]:
def predict(parameters,X):
    '''
    Input:
        parameters:A tuple containing weights and bias
        X:Input Data
    Output:
        predicted: Predicted values on our data
    '''
    w=parameters[0]
    b=parameters[1]
    z=np.dot(w,X)+b
    a=sigmoid(z)
    
    predicted=np.around(a)
    return predicted

In [404]:
def model(X,Y,alpha,num_iterations):
    '''
    Input:
        X:Input Data
        Y:Output Data
        alpha:Learning rate
        num_iterations:number of iterations for which gradient descent is run
    Output:
        parameter: parameter obtained after applying gradient descent
        cost:List of cost containing values of cost after every 100 iterations
        accuracy: Accuracy obtained on Input Data
    '''
    parameters=initialize_weights(X,Y)
    cost,parameter,gradient=optimize(alpha,parameters,X,Y,num_iterations)
    Y_predicted=predict(parameter,X)
    m=Y.shape[1]
    count=0
    for i in range(m):
        if(Y_predicted[0][i]==Y[0][i]):
            count+=1        
    accuracy=count/m*100
    return parameter,cost,accuracy